language: python
sudo: required


python:
  - '3.6'
  - '3.5'

matrix:
  include:
    - python: '3.6'
      env: AIOHTTP_MASTER="y"
    - python: '3.6'
      env: MYPY="y"
  allow_failures:
    - env: AIOHTTP_MASTER="y"

install:
    - pip install --upgrade setuptools
    - pip install codecov
    - pip install -r requirements-dev.txt
    - |
        if [ "$AIOHTTP_MASTER" = "y" ]; then
            pip install cython
            pip install https://github.com/aio-libs/aiohttp/archive/master.zip
        fi;
    - |
        if [ "$MYPY" = "y" ]; then
            make mypy
        fi;

script:
    make cov
after_success:
    codecov

deploy:
  provider: pypi
  user: aio-libs-bot
  distributions: sdist bdist_wheel
  password:
    secure: NqB+19j1K/PZ7p655dQQje4EA8YEkCxqPIJsX+xznu+B8YG8zzbUXMeIBOOj3O1wdXYq01vBw98a+Tl/kRzJ/jfEkMR7JiZUhVyH4K4gNlOfRMlDfyhv3vIEdwWaIDmavfjIaZlqyPjbM42taejr5Z33aryJgi6ev6dpBZwrhdTYZ13tzWeKs0fK3F3ewD7wJP8a9wx0hVIGSKbBSYA7WQCiPjaajuPLeCfb8O4Q3ny3zWy0XW7c5PFIUF3+WWXVmJYGZKn6bLP3yKJLPHfeDHE9Iq+iloRvoJIuwJ8xMMlA35DGwxiPBgp3aZrV44WiFEZHGaYRkfK8azXRjWw3k+CZwUvOoMxfRi2DcJsoci07uNCTdt0GIi92hahcI4NTE+sQjtNPeGsJgEQlMQmEWxfg/B0hxrmw0plemf1leOcQ8feOB2I4dfTmlnZCdsoRjh5dhWplc0lXdx4cApgWZTJbRY2Sys6nWgqRQWdyZvU7W8qQSAIzIu4DEGkFeZCDAzvxcVGsJH8EuWdOak3oOxInmmQxcHPz5Bc/kjo5XsrLT8JGJ7QLPytNlJWUadXvf3iqnNDk+3Q66ACVnjpLjoek0ycwVDI0rQzKOrhDps9MhJJsgyO2dYHZxSpiqS7b1jXi1A5X6eok7ZhEYPx58l9tun3edNKrJ0QdiAkcmTg=
  on:
    tags: true
    repo: aio-libs/aiozipkin
    all_branches: true
    python: 3.6
